name: Ren'Py 生成

# 在这里定义触发工作流程的事件组
on:
  push:
  pull_request:
  release:
    types: [created]

# 定义作业和它的步骤
jobs:
  build:
    name: 使用 Ren'Py SDK 生成
    runs-on: ubuntu-latest

    steps:
      - name: 克隆 repo
        uses: actions/checkout@v1
        with:
          submodules: true

      # 确保代码可行
      - name: 检查脚本
        uses: ProjectAliceDev/renpy-lint-action@master
        with:
          sdk-version: '7.3.5'
          project-dir: .
        env:
          # GitHub Actions 环境下没有 GUI
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy

      # 生成项目
      - name: 生成 VN
        uses: Dobby233Liu/renpy-build-action@master
        # 定义一个 ID 以便之后使用
        id: buildseq
        with:
          sdk-version: '7.3.5'
          project-dir: .
          extra-options: '--package market'
        env:
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy

      # 将生成的 zip 上传
      - name: 上传生成的 zip 到 GitHub Actions
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.buildseq.outputs.dir }}
          path: ${{ format('{0}/{1}-market.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}

      # 将生成的 zip 上传到一个刚创建的 Release 里
      - name: 上传生成的 zip 到 Release
        uses: skx/github-action-publish-binaries@master
        if: github.event.release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ format('{0}/{1}-market.zip', steps.buildseq.outputs.dir, steps.buildseq.outputs.version) }}

  build-rapt:
    name: 使用 RAPT 生成
    runs-on: ubuntu-latest

    steps:
      - name: 克隆 repo
        uses: actions/checkout@v1
        with:
          submodules: true

      # 确保代码可行
      - name: 检查脚本
        uses: ProjectAliceDev/renpy-lint-action@master
        with:
          sdk-version: '7.3.5'
          project-dir: .
        env:
          # GitHub Actions 环境下没有 GUI
          SDL_AUDIODRIVER: dummy
          SDL_VIDEODRIVER: dummy

      - name: 初始化 JDK
        uses: actions/setup-java@master
        with:
            java-version: 8
      - name: 初始化 Python
        uses: actions/setup-python@master
        with:
            python-version: 2.7
      - name: 下载 RAPT
        run: |
            cd ~
            wget https://www.renpy.org/dl/7.3.5/renpy-7.3.5-sdk.zip -q
            unzip -o renpy-7.3.5-sdk.zip
            cd renpy-7.3.5-sdk
            wget https://www.renpy.org/dl/7.3.5/renpy-7.3.5-rapt.zip -q
            unzip -d rapt -j -o renpy-7.3.5-rapt.zip
      - name: 安装 pygame_sdl2
        run: |
            cd ~
            sudo apt-get install libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0 libsdl2-dev libsdl2-2.0-0 libsdl2-2.0
            wget https://www.renpy.org/dl/7.3.5/pygame_sdl2-2.1.0-for-renpy-7.3.5.tar.gz -q
            tar -xzf pygame_sdl2-2.1.0-for-renpy-7.3.5.tar.gz
            cd pygame_sdl2-2.1.0-for-renpy-7.3.5
            python2 setup.py install
      - name: 初始化 RAPT 用 Android SDK
        run: |
            cd ~/renpy-7.3.5-sdk/rapt
            python2 android.py installsdk
      - name: 生成 APK
        run: python2 ~/renpy-7.3.5-sdk/rapt/android.py build . assembleDebug
